site_name: TensorFlow Data Transform
repo_name: "transform"
repo_url: https://github.com/tensorflow/transform

theme:
  logo: images/tf_full_color_primary_icon.svg
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: custom
      accent: custom
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: custom
      accent: custom
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  favicon: images/tf_full_color_primary_icon.svg

  features:
    - content.code.copy
    - content.code.select
    - content.action.edit

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            unwrap_annotated: true
            show_symbol_type_toc: true
            show_if_no_docstring: true
            show_symbol_type_heading: true
            merge_init_into_class: true
            show_signature_annotations: true
            separate_signature: true
            signature_crossrefs: true
            group_by_category: true
            show_category_heading: true
            show_submodules: false
            show_root_full_path: true
            docstring_section_style: "spacy"
            inherited_members: true
            summary: false
            filters:
              - "!^_"
              - "^__init__$"
              - "^__call__$"
              - "^__version__$"
              - "!^logger"
              - "!^test_"
              - "!_test$"
            extensions:
              - griffe_inherited_docstrings
            preload_modules:
                - apache_beam
          load_external_modules: true
          inventories:
            - https://docs.python.org/3/objects.inv
            - https://beam.apache.org/releases/pydoc/current/objects.inv
  - mkdocs-jupyter:
      ignore_h1_titles: True
  - caption

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - tables
  - markdown_grid_tables
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: false
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
watch:
  - tensorflow_transform

nav:
  - Preprocess and transform data: index.md
  - Guide:
      - Install: install.md
      - Get Started: get_started.ipynb
      - Using tf.Transform with TensorFlow 2.x: tf2_support.md
      - Common Transformations: common_transformations.md
      - Data preprocessing best practices: tft_bestpractices.md
  - API:
      - tft: api_docs/python/tft.md
      - tft.coders: api_docs/python/tft-coders.md
      - tft.experimental 🧪: api_docs/python/tft-experimental.md
      - tft.beam: api_docs/python/tft-beam.md
      - tft.beam.analyzer_cache: api_docs/python/tft-beam-analyzer-cache.md
      - tft.beam.experimental 🧪: api_docs/python/tft-beam-experimental.md
