# Github action definitions for unit-tests with PRs.

name: tft-unit-tests
on:
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  workflow_dispatch:
  push: # DEBUG: Remove before merge

jobs:
  unit-tests:
    if: github.actor != 'copybara-service[bot]'
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'
        cache-dependency-path: |
          setup.py

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade wheel setuptools
        python -m pip install -e .[test]

    - name: Run unit tests
      shell: bash
      run: |
        pytest 
